apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-byond-app
  ports:
    - protocol: "TCP"
     port: 6000
     targetPort: 5000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
name: flask-byond-app
spec:
  selector:
    matchLabels:
      app: flask-byond-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-byond-app
    spec:
      containers:  
      - name: flask-test-app
        image: docker.io/<username>/flask-kubernetes-app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000

---
 
